spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jubjub?serverTimezone=Asia/Seoul
    username: root
    password: 316298

  jpa:
    defer-datasource-initialization: true # Hibernate 초기화 후 data.sql 실행
    hibernate:
      ddl-auto: update  # ?? ??? Entity? ?? DB ???? ???? ??? ??/??????.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # ?? ?? ?? ???(N+1 ?? ??)? ?? ??? ?? ?? ??!
  sql:
    init:
      mode: always # 항상 SQL 초기화 실행


# P6Spy ?? ??? ?? ?? (?? ??? ??????)
decorator:
  datasource:
    p6spy:
      enable-logging: true

jwt:
  # secret과 expiration-time은 스페이스바 2칸 들여쓰기!
  secret: JubJubDeliveryAppSecretKeyForJwtTokenGeneration2024
  expiration-time: 86400000