spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jubjub?serverTimezone=Asia/Seoul
    username: root
    password: 316298

  jpa:
    hibernate:
      ddl-auto: update  # ?? ??? Entity? ?? DB ???? ???? ??? ??/??????.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000 # ?? ?? ?? ???(N+1 ?? ??)? ?? ??? ?? ?? ??!

# P6Spy ?? ??? ?? ?? (?? ??? ??????)
decorator:
  datasource:
    p6spy:
      enable-logging: true